services:
  mysql_db:
    container_name: "mysql_db"
    image: "mysql/mysql-server:8.0.32"
    restart: "always"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "inventory-service"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"